# Generated by Django 4.2.11 on 2025-10-08 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='banking.bank')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_invoice', to='sales.invoice')),
            ],
        ),
    ]
