# Generated by Django 5.2.4 on 2025-10-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_bank_opening_balance_bank_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.bank'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='banking.bank'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
