# Generated by Django 5.2.4 on 2025-08-12 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
