# Generated by Django 5.2.4 on 2025-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='detail',
            field=models.CharField(max_length=255),
        ),
    ]
