# Generated by Django 5.2.4 on 2025-10-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_barcode_remove_product_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='selling_price_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_selling_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
