# Generated by Django 4.2.11 on 2025-10-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stockin_selling_price_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='selling_price',
        ),
    ]
