# Generated by Django 4.2.11 on 2025-10-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_invoice_payment_method_and_more'),
        ('products', '0008_remove_stockout_buying_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockout',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='stockout',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_stockout', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='stock_out_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
